# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
bio = Bio.create([{content: 'Tiago Belém é hoje um músico de destaque no meio musical. Destaque construído por seu talento precoce, dedicação e muito profissionalismo. Adjetivos que o permitiram dividir palco com grandes artistas consagrados da música brasileira. Nomes como: Rosana, Peninha, Paulinhos Mosca, Marlon & Maicon, Cindy Black (seriado Antônia - Rede Globo), As Leoas (Programa Gilberto Barros - BAND), Léo Maia, Netinho (Negritude Jr.), Cláudio Zoli, Simoninha, Beto Barbosa, Wilson Sideral, Pedro la Colina, Gimerlândia (Banda Beijo), Liah Soares (The Voice Brasil), entre outros.

Com enorme experiência em variados estilos musicais, acompanhou e gravou com cantores e bandas regionais e nacionais como: Orquestra Asafe (PA), Orquestra do Templo Central da Assembléia de Deus (PA), Banda Sevilha (PA), Lú Guedes (PA), Augusto Hijo (PA), Rafael Naleto (PA), Banda Matrakaloka (SP), Banda Luna Nueva (SP), Angelica Sansane (Bar Brahma- SP), Jurema Paes (Baile do Bolero - SP), Keila Vilaça (Ídolos 2007- SBT), Carla Maúes (Banda Zoukaliente - SP), Larissa Cavalcante (SP), Tchelo Hit (SC), Sandro & Fabiano (PA), Cacau Novaes (PA), Gigi Furtado (PA), Wiliam Cezar & Cristiano (PA), Breno & Mackoy (SP), Kayo & Marcelo(PA), Adriana Cavalcante (PA), Banda Making Of (PA), André & Tiago (PA), Joba (PA), Orquestra SAM BAND (EMUFPA), Lucinha Bastos (PA), Nilson Chaves (PA), Simone Almeida (PA), Pastor Aziel Neves (PA), Rogério Brito (PA), Ângelo Carlo (PA), Daise Adário (PA), Pastor Jonas Villar(SP), Larissa White (AUSTRÁLIA), Gigi Furtado (PA), Zarabatana Jazz Band (PA), Alba Maria (PA), Daniel Lima (PA), Grupo Celebrai (PA), Pedrinho Calado (PA), Nathalia Matos (PA), Kayo Reiz (PA), Lídia Gonçalves (PA), Olivar Barreto (PA), Patrícia Queiroz (PA), entre outros.

Em paralelo as atividades como "Side Man" , esteve ao lado de grandes músicos do cenário instrumental, tais como: Celso Pixinga (solo), Gileno Foinquinas (Bacata), Ney Conceição (solo), Claudio Machado (EM&T SP), Trio Manarin, Esdras de Souza, Priamo Brandão, Harley Bichara, Jó Ribeiro, Adelbert Carneiro, Cassius Colozans (Léo Maia), Jonas Dantas, Bruno Migoto (Soundscape), Ximba Uchiama (três de paus), Denis Lisboa (ex-músico do Carlinhos Brown), Marcelo Costa (ex-músico da Banda Beijo), Orlando Balão (Cheiro de Amor), Pit Cajonero, Javier Ibanez, Pio (Alexandre Pires), Deny Conceição (Natiruts), Augusto Babu Castro, Bráulio Aráujo (RN), MG Calibre, Alcir Meireles, Beto Meireles, Marcus Puff, Jacinto Kawage, Delclei Machado, Ziza Padilha, Luiz Pardal, Davi Amorin Angelo Barros, Lenilson Albuquerque, Elias Coutinho, Walter Almeida, entre outros.

Na área acadêmica, sempre se dedicou ao ensino musical, Tem formação no seu instrumento pelo Instituto Carlos Gomes. Estudo na EM&T - SP, além de aperfeiçoar sua técnica em vários músicos de renome nacional e internacional, tais como: Mariano Primo (Amazônia Jazz Band), Ricardo Aquino (OSTP), Edér Luis (Bateras Beat - São Paulo), Douglas Las Casas (solo), Cristiano Rocha (EM&T - SP e músico da cantora Eugênia Melo e Castro), Daniel Baeder (Cirque Du Solei), Dom Moio (EUA), Kiko Freitas (João Bosco), Maurício Leite, Workshops com Vera Figueiredo (Batuka - SP), Aquiles Priester, Cuca Teixeira, Bob White(EUA), Alaor Neves, Carlos Ezequieu, Albino Infantozzi, Cláudio Infante, Fabiano Manhas, entre outros.

Atualmente, acompanha a cantora Liah Soares (The Voice Brasil), atua com seu trio instrumental Toque Fino, integra a trio Andaluz ao lado de Luiz Pardal e Jacinto Kawage, é baterista do ZARABATA JAZZ BAND e atua como "Side Man", tocando, ensaiando e gravando com diversos artistas.

Seu primeiro projeto solo é o disco Influências. Músicas que retratam todas as influências que o músico carrega ao longo de sua carreira. Ao seu lado músico consagrados do senário paraensee participações de artistas nacionais. O projeto, além do disco, prevê show de lançamento e circulação de workshops e shows.'}])